services:
  - type: web
    name: otp-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn OTP.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DJANGO_SETTINGS_MODULE
        value: OTP.settings
